apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata: {name: ps-imagenet-bs32-pserver}
spec:
  replicas: 4
  template:
    metadata:
      labels: {paddle-job-pserver: ps-imagenet-bs32}
    spec:
      nodeSelector:
        wuyinode: "2"
      containers:
      - command: [paddle_k8s, start_fluid]
        env:
        - {name: GLOG_v, value: '0'}
        - {name: GLOG_logtostderr, value: '1'}
        - {name: TOPOLOGY, value: ''}
        - {name: TRAINER_PACKAGE, value: /workspace}
        - {name: PADDLE_INIT_NICS, value: eth2}
        - name: NAMESPACE
          valueFrom:
            fieldRef: {fieldPath: metadata.namespace}
        - name: POD_IP
          valueFrom:
            fieldRef: {fieldPath: status.podIP}
        - name: PADDLE_CURRENT_IP
          valueFrom:
            fieldRef: {fieldPath: status.podIP}
        - {name: PADDLE_JOB_NAME, value: ps-imagenet-bs32}
        - {name: PADDLE_TRAINERS, value: '4'}
        - {name: PADDLE_PSERVERS, value: '4'}
        - {name: FLAGS_rpc_deadline, value: '36000000'}
        - {name: ENTRY, value: cd /workspace && NCCL_SOCKET_IFNAME=eth2 NCCL_IB_DISABLE=0
            NCCL_IB_GID_INDEX=3 NCCL_DEBUG=INFO python fast_imagenet_train.py --model
            resnet_lars --data_set imagenet --gpus 8 --update_method pserver --iterations
            -1 --batch_size 32 --pass_num 120 --data_path /mnt/ImageNet --test_data_path
            /mnt/ImageNet --learning_rate 0.1  --multi_batch_repeat 8}
        - {name: PADDLE_PSERVER_PORT, value: '30236'}
        - {name: LD_LIBRARY_PATH, value: '/usr/local/lib:/usr/local/nvidia/lib64:/usr/local/rdma/lib64:/usr/lib64/mlnx_ofed/valgrind'}
        - {name: PADDLE_TRAINING_ROLE, value: PSERVER}
        image: bootstrapper:5000/fluid_benchmark:gpu
        imagePullPolicy: Always
        name: pserver
        ports:
        - {containerPort: 30236, name: jobport-30236}
        volumeMounts:
        - {mountPath: /mnt/seqdata, name: seqdata}
        resources:
          limits: {cpu: '10', memory: 30Gi}
          requests: {cpu: '4', memory: 30Gi}
      hostNetwork: true
      imagePullSecrets:
      - {name: job-registry-secret}
      volumes:
      - hostPath: {path: /home/work/wuyi/seqdata}
        name: seqdata
